# Fails to receive and logs messages.
apiVersion: v1
kind: Pod
metadata:
  name: sink-nack-conformance
  namespace: conformance
  labels:
    component: conformance-sink
    app: sink-nack-conformance
spec:
  containers:
  - name: sink-nack-conformance
    image: pmercado/recordevents
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: SYSTEM_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: EVENT_GENERATORS
      value: receiver
    - name: EVENT_LOGS
      value: logger
    - name: REPLY
      value: "false"
      # Return NACK 3 first times. Combining this with a
      # subscription delivery that does not send retries will
      # result in a single NACK of the first request.
    - name: SKIP_ALGORITHM
      value: sequence
    - name: SKIP_COUNTER
      value: "3"

    ports:
    - containerPort: 8080

---

# Expose recordevents as a service
apiVersion: v1
kind: Service
metadata:
  name: sink-nack-conformance
  namespace: conformance
spec:
  selector:
    app: sink-nack-conformance
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080

---

apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: sink-nack-conformance
  namespace: conformance
spec:
  channel:
    apiVersion: messaging.knative.dev/v1
    kind: InMemoryChannel
    name: conformance-channel
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: sink-nack-conformance
  # Disable retries to make sure that failed events are
  # not retried.
  delivery:
    retry: 0

