# Fails to receive first 3 and logs messages.
apiVersion: v1
kind: Pod
metadata:
  generateName: sink-3nack-
  namespace: conformance
  labels:
    app: conformance
    case: broker-retry-exponential
    component: sink-3nack
spec:
  containers:
  - name: sink-3nack
    image: gcr.io/knative-nightly/knative.dev/eventing/test/test_images/recordevents@sha256:9daab3dca38eabe00287512a430ef6c378d43ccab707ea7e240ea748c5ac32c5
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: SYSTEM_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: EVENT_GENERATORS
      value: receiver
    - name: EVENT_LOGS
      value: logger,recorder
    - name: REPLY
      value: "false"
      # Return NACK 3 first times. Combining this with a
      # subscription delivery that retries 3 times will
      # result in 3 first events NACK, then ACK.
    - name: SKIP_ALGORITHM
      value: sequence
    - name: SKIP_COUNTER
      value: "3"

    ports:
    - containerPort: 8080

---

# Expose recordevents as a service
apiVersion: v1
kind: Service
metadata:
  name: sink-3nack
  namespace: conformance
  labels:
    app: conformance
    case: broker-retry-exponential
spec:
  selector:
    app: conformance
    case: broker-retry-exponential
    component: sink-3nack
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080

---

apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: broker-retry-exponential
  namespace: conformance
  labels:
    app: conformance
    case: broker-retry-exponential
spec:
  broker: conformance-broker
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: sink-3nack
  # Set retries to 3 and backoff to 2 seconds.
  delivery:
    retry: 3
    backoffPolicy: exponential
    backoffDelay: PT2S
