# Receives and logs messages, producing a reply.
apiVersion: v1
kind: Pod
metadata:
  generateName: sink-ack-reply-
  namespace: conformance
  labels:
    app: conformance
    case: broker-reply
    component: sink-ack-reply
spec:
  containers:
  - name: sink-ack-reply
    image: gcr.io/knative-nightly/knative.dev/eventing/test/test_images/recordevents@sha256:9daab3dca38eabe00287512a430ef6c378d43ccab707ea7e240ea748c5ac32c5
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: SYSTEM_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: EVENT_GENERATORS
      value: receiver
    - name: EVENT_LOGS
      value: logger,recorder
    - name: REPLY
      value: "true"
    - name: REPLY_EVENT_TYPE
      value: "com.example.conformance.reply"
    - name: REPLY_EVENT_SOURCE
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: REPLY_EVENT_DATA
      value: '{"conformance":"response message"}'
    ports:
    - containerPort: 8080

---

# Expose recordevents as a service
apiVersion: v1
kind: Service
metadata:
  name: sink-ack-reply
  namespace: conformance
  labels:
    app: conformance
    case: broker-reply
spec:
  selector:
    app: conformance
    case: broker-reply
    component: sink-ack-reply
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080

---

# Receives and logs messages.
apiVersion: v1
kind: Pod
metadata:
  generateName: sink-ack-
  namespace: conformance
  labels:
    app: conformance
    case: broker-reply
    component: sink-ack
spec:
  containers:
  - name: sink-ack
    image: gcr.io/knative-nightly/knative.dev/eventing/test/test_images/recordevents@sha256:9daab3dca38eabe00287512a430ef6c378d43ccab707ea7e240ea748c5ac32c5
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: SYSTEM_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: EVENT_GENERATORS
      value: receiver
    - name: EVENT_LOGS
      value: logger,recorder
    - name: REPLY
      value: "false"
    ports:
    - containerPort: 8080

---

# Expose recordevents as a service
apiVersion: v1
kind: Service
metadata:
  name: sink-ack
  namespace: conformance
  labels:
    app: conformance
    case: broker-reply
spec:
  selector:
    app: conformance
    case: broker-reply
    component: sink-ack
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080

---

apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: sink-reply
  namespace: conformance
  labels:
    app: conformance
    case: broker-reply
spec:
  broker: conformance-broker
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: sink-ack-reply
  # Only process events produced from sink-ack-conformance
  filter:
    attributes:
      type: com.example.conformance
  # Disable retries to make sure that failed events are
  # not retried.
  delivery:
    retry: 0

---

apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: sink-ack
  namespace: conformance
  labels:
    app: conformance
    case: broker-reply
spec:
  broker: conformance-broker
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: sink-ack
  # Only process events produced from sink-ack-conformance
  filter:
    attributes:
      type: com.example.conformance.reply
  # Disable retries to make sure that failed events are
  # not retried.
  delivery:
    retry: 0



