/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
	v1alpha1 "knative.dev/sample-source/pkg/apis/samples/v1alpha1"
)

// SampleSourceLister helps list SampleSources.
type SampleSourceLister interface {
	// List lists all SampleSources in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.SampleSource, err error)
	// SampleSources returns an object that can list and get SampleSources.
	SampleSources(namespace string) SampleSourceNamespaceLister
	SampleSourceListerExpansion
}

// sampleSourceLister implements the SampleSourceLister interface.
type sampleSourceLister struct {
	indexer cache.Indexer
}

// NewSampleSourceLister returns a new SampleSourceLister.
func NewSampleSourceLister(indexer cache.Indexer) SampleSourceLister {
	return &sampleSourceLister{indexer: indexer}
}

// List lists all SampleSources in the indexer.
func (s *sampleSourceLister) List(selector labels.Selector) (ret []*v1alpha1.SampleSource, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.SampleSource))
	})
	return ret, err
}

// SampleSources returns an object that can list and get SampleSources.
func (s *sampleSourceLister) SampleSources(namespace string) SampleSourceNamespaceLister {
	return sampleSourceNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// SampleSourceNamespaceLister helps list and get SampleSources.
type SampleSourceNamespaceLister interface {
	// List lists all SampleSources in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.SampleSource, err error)
	// Get retrieves the SampleSource from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.SampleSource, error)
	SampleSourceNamespaceListerExpansion
}

// sampleSourceNamespaceLister implements the SampleSourceNamespaceLister
// interface.
type sampleSourceNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all SampleSources in the indexer for a given namespace.
func (s sampleSourceNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.SampleSource, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.SampleSource))
	})
	return ret, err
}

// Get retrieves the SampleSource from the indexer for a given namespace and name.
func (s sampleSourceNamespaceLister) Get(name string) (*v1alpha1.SampleSource, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("samplesource"), name)
	}
	return obj.(*v1alpha1.SampleSource), nil
}
