apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: conformance-trigger
  namespace: default
spec:
  broker: non-existent-broker
  subscriber:
    uri: http://events-counter-service.default.svc.cluster.local/events